### ISSUE TITLE
wrong typo in docker-compose.yml

### ISSUE THREAD

**Issue by ADeeeee** [CommunityHoneyNetwork/elasticpot#1]
Hi folks,

I'm not sure if it's by design or a mistake. Here it is in the docker-compose.yml, which should be elasti`c`pot:

version: '3'
services:
  **elastipot**:
    build:
      context: .
    volumes:
      - configs:/etc/**elastipot**
    ports:
      - "9200:9200"
    env_file:
      - elasticpot.env
volumes:
  configs:

It doesn't matter with the container name, but it should mount the wrong folder, which made me opening this issue.

**Comment by JesseBowling** [comment]
Hi!

Sure enough, that typo is in the docker-compose for the distro! It looks like the deployment script provided with CHN-Server (at least in master) has this correct. 

I've fixed the elasticpot repo docker-compose.yml in master; please pull that version if deploying via repo! :)

**Comment by JesseBowling** [comment]
As an aside, not sure the webhook that would normally notify us of this didn't fire until this morning, but that's the reason for the delay. ¯\_(ツ)_/¯
